# Generated by Django 3.2.3 on 2021-05-15 09:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DontateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Donate to SOS Romanian Rescues South West', max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Body')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Configuration',
            },
        ),
    ]
