# Generated by Django 3.2.3 on 2021-05-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('dontate_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.dontatesettings')),
            ],
        ),
    ]
