# Generated by Django 3.2.3 on 2021-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='values',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='values',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
