# Generated by Django 3.2.3 on 2021-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20210515_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontatesettings',
            name='button_text',
            field=models.CharField(default='Donate to SOS Romanian Rescue', max_length=255, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='dontatesettings',
            name='title',
            field=models.CharField(default='Donate to SOS Romanian Rescues South West', max_length=255, verbose_name='Title'),
        ),
    ]
