engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
  fixme:
    enabled: true
  pep8:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - '**.py'
  - '**.js'
exclude_paths:
- '**/migrations/**/*.py'
- pages/static/pages/css/**/*.css
- pages/static/pages/js/**/*.js
- Gruntfile.js
