pull_request_rules:
  - name: Automatic approve on dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=workflow
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=workflow
    actions:
      merge:
        method: merge

  - name: Automatic approve on Sourcery AI PR
    conditions:
      - author~=^sourcery.*$
      - check-success=workflow
    actions:
      review:
        type: APPROVE

  - name: Automatic merge on approval of Sourcery AI PR
    conditions:
      - author~=^sourcery.*$
      - check-success=workflow
    actions:
      merge:
        method: merge