# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'migrations/.*\.py|Procfile|[aw]sgi\.py|node_modules|.git|\.polar'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
    - id: absolufy-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.15.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place]
  - repo: https://github.com/hadialqattan/pycln
    rev: 0.0.2
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.1.0
    hooks:
      - id: pip-compile
        files: ^(setup\.py|requirements.in)$
        args: [--no-emit-index-url]
      - id: pip-compile
        files: ^requirements.dev.in$
        args: [--no-emit-index-url, -o requirements.dev.txt, requirements.dev.in]
