language: python
python:
- 2.7.14
services: postgresql
env:
- DJANGO=1.11.5
before_install:
- export DJANGO_SETTINGS_MODULE=romrescue.settings
- export PYTHONPATH=$HOME/builds/bengosney/romrescue.org
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE romrescue;" -U postgres
- python manage.py collectstatic --no-input
script:
- python manage.py test
notifications:
  slack:
    secure: NUEvEWzYxsafAPnPQVXXXwbEV+hkUkoaqaYPGUSStBoEUchWXNbZ5pJSGcT3pG1rXNGRbI6GSvuesYRV2Jx3DeExiS8hxvXec9OW9oyMw5nrxxqiQohu9PKiNhK44aj+oDnySuUFpcAAYo1M7h77GEo6MXljwPHKi0tcRHJMskpszEqB8qZA2Ztb1HmGIy3sYeP2b/75yrA372u7iew7VPM17JoxvPb/L0d2YNCoRHf/deF5pPNXpkd+GRwsqsYUsgU0egUUY/yd2RvTqo4zoTwqunZZFg9IeQt1Wwsmaf8DX7zzp7hiUojsKLfPySOy/wuQxB9E4GsaZy+UIVuS+oBGnzmMYFtSn1AY1+cd1bF7MpOKXncKBoWs2AnsqsuWm/giCvvyT941iT8Z5hLf+DQnID+A2/Lu/pbEz59I41NqPfyS3cafL9+RypXuXKKlvSLmWsFb0QpNj/7mq5E1k3+WkAQQD8w7A77mDagGUk6ToNenoxP4UAnaAFmL0g8C9wD1hwZOvBUojp3SbVh/1HeNsKwu81n3vye3/KOg3zgc2wthlRdO//iSXwfSn6j3131qWT6RCsCI8bBx8wBfufR/JRu/2WaZaML9t4qbbrV8nLs7dpPs6pIEyqn6h71Pyw1gdQQwI2coyxfEDXiHwCKigeNmXI7j+SAlWo8FYCA=
