language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.9.7

before_install:
  - export DJANGO_SETTINGS_MODULE=romrescue.settings
  - export PYTHONPATH=$HOME/builds/bengosney/romrescue.org
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE romrescue;" -U postgres

script:
#  - python manage.py migrate --noinput
  - python manage.py test