dist: xenial
language: python
python:
  - 3.7
services: postgresql
cache: pip
before_install:
  - export DJANGO_SETTINGS_MODULE=romrescue.settings
  - export PYTHONPATH=$HOME/builds/bengosney/romrescue.org
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install psycopg2 --quiet
before_script:
  - psql -c "CREATE DATABASE romrescue;" -U postgres
  - python manage.py collectstatic --no-input
script:
  - python manage.py test
