# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 22:51
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    setting = apps.get_model("websettings", "setting")


class Migration(migrations.Migration):
    dependencies = [
        ('websettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
