# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('Info', models.CharField(max_length=500, verbose_name='Info')),
                ('image', models.ImageField(upload_to='images/team')),
                ('cropped', image_cropping.fields.ImageRatioField('image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
