# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='Info',
        ),
        migrations.AddField(
            model_name='teammember',
            name='info',
            field=models.TextField(default='No info', max_length=500, verbose_name='Info'),
            preserve_default=False,
        ),
    ]
