# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20160730_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='info',
            field=models.TextField(max_length=1000, verbose_name='Info'),
        ),
    ]
