# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20161029_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogphoto',
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='DogPhoto',
        ),
    ]
