# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20161029_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/team'),
        ),
    ]
