# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 21:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('size', models.CharField(choices=[('extra small', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra large', 'Extra Large')], max_length=15)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Body')),
                ('status', models.CharField(choices=[('looking', 'Looking for a home'), ('found', 'Found a home'), ('success', 'Success storie')], default='looking', max_length=8)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
            },
        ),
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/dogs')),
                ('thumbnail', image_cropping.fields.ImageRatioField('image', '375x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail')),
                ('position', models.PositiveIntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=400)),
                ('position', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, choices=[(b'', 'Select an icon'), (b'dog-and-a-man', 'dog-and-a-man'), (b'dog-and-pets-house', 'dog-and-pets-house'), (b'dog-bitting-a-stick-playing-with-a-man', 'dog-bitting-a-stick-playing-with-a-man'), (b'dog-checked-by-a-veterinary', 'dog-checked-by-a-veterinary'), (b'dog-having-a-bubbles-bath', 'dog-having-a-bubbles-bath'), (b'dog-in-front-of-a-man', 'dog-in-front-of-a-man'), (b'dog-learning-man-instructions', 'dog-learning-man-instructions'), (b'dog-playing-with-a-man', 'dog-playing-with-a-man'), (b'dog-pooping', 'dog-pooping'), (b'dog-puppy-and-his-owner-looking-to-opposite-directions', 'dog-puppy-and-his-owner-looking-to-opposite-directions'), (b'dog-puppy-sitting-in-front-of-his-man', 'dog-puppy-sitting-in-front-of-his-man'), (b'dog-smelling-a-bone', 'dog-smelling-a-bone'), (b'dog-with-belt-walking-with-a-man', 'dog-with-belt-walking-with-a-man'), (b'dog-with-first-aid-kit-bag', 'dog-with-first-aid-kit-bag'), (b'dog-with-owner', 'dog-with-owner'), (b'man-carrying-a-dog-with-a-belt-to-walk', 'man-carrying-a-dog-with-a-belt-to-walk'), (b'man-combing-a-dog', 'man-combing-a-dog'), (b'man-on-his-knees-to-cuddle-his-dog', 'man-on-his-knees-to-cuddle-his-dog'), (b'man-throwing-a-disc-and-dog-jumping-to-catch-it', 'man-throwing-a-disc-and-dog-jumping-to-catch-it'), (b'paws-up-dog-playing-with-a-man', 'paws-up-dog-playing-with-a-man'), (b'facebook-square', 'facebook-square'), (b'google-plus-square', 'google-plus-square'), (b'pinterest-square', 'pinterest-square'), (b'twitter-square', 'twitter-square')], max_length=120)),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Key Point',
                'verbose_name_plural': 'Key Points',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Body')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Status/Location',
                'verbose_name_plural': 'Status/Locations',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='keypoints',
            field=models.ManyToManyField(blank=True, null=True, to='dogs.KeyPoints'),
        ),
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Status'),
        ),
    ]
