# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20160617_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='status',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
