# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20160730_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoints',
            name='status',
            field=models.IntegerField(choices=[(1, b'Live'), (2, b'Draft'), (3, b'Hidden')], default=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='keypoints',
            field=models.ManyToManyField(blank=True, to='dogs.KeyPoints'),
        ),
    ]
