# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20160617_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('position',), 'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
