# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20160617_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogphoto',
            old_name='project',
            new_name='dog',
        ),
    ]
