# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20160618_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogphoto',
            options={'ordering': ('position',), 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='dog',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dogs.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
