# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_dog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
