# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_auto_20160618_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('extra small', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra large', 'Extra Large')], max_length=15),
        ),
    ]
