# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='neutered',
            field=models.BooleanField(default=True),
        ),
    ]
