# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_auto_20160626_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='status',
            new_name='location',
        ),
    ]
