# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_auto_20160626_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=400)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Key Point',
                'verbose_name_plural': 'Key Points',
            },
        ),
    ]
