# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_dog_neutered'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='standard_info',
            field=models.BooleanField(default=True),
        ),
    ]
