# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_dog_standard_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='leash_of_life',
            field=models.BooleanField(default=False),
        ),
    ]
