# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_dog_leash_of_life'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='uploads/rescue')),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': 'Rescue',
                'verbose_name_plural': 'Rescues',
            },
        ),
    ]
