# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_keypoints_dogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypoints',
            name='dogs',
        ),
        migrations.AddField(
            model_name='dog',
            name='keypoints',
            field=models.ManyToManyField(to='dogs.KeyPoints'),
        ),
    ]
