# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:41
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_auto_20160628_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogphoto',
            name='crop',
            field=image_cropping.fields.ImageRatioField('image', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='crop'),
        ),
    ]
