# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_rescue'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='rescue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.Rescue'),
        ),
    ]
