# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_dog_rescue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='leash_of_life',
        ),
    ]
