# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:53
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_dogphoto_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogphoto',
            name='crop',
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='thumbnail',
            field=image_cropping.fields.ImageRatioField('image', '375x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='thumbnail'),
        ),
    ]
