# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0013_auto_20160629_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('position',), 'verbose_name': 'Status/Location', 'verbose_name_plural': 'Status/Locations'},
        ),
        migrations.AddField(
            model_name='keypoints',
            name='icon',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
