# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0014_auto_20160702_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoints',
            name='icon',
            field=models.CharField(blank=True, choices=[(b'', 'Select an icon'), (b'dog-and-a-man', 'dog-and-a-man'), (b'dog-and-pets-house', 'dog-and-pets-house'), (b'dog-bitting-a-stick-playing-with-a-man', 'dog-bitting-a-stick-playing-with-a-man'), (b'dog-checked-by-a-veterinary', 'dog-checked-by-a-veterinary'), (b'dog-having-a-bubbles-bath', 'dog-having-a-bubbles-bath'), (b'dog-in-front-of-a-man', 'dog-in-front-of-a-man'), (b'dog-learning-man-instructions', 'dog-learning-man-instructions'), (b'dog-playing-with-a-man', 'dog-playing-with-a-man'), (b'dog-pooping', 'dog-pooping'), (b'dog-puppy-and-his-owner-looking-to-opposite-directions', 'dog-puppy-and-his-owner-looking-to-opposite-directions'), (b'dog-puppy-sitting-in-front-of-his-man', 'dog-puppy-sitting-in-front-of-his-man'), (b'dog-smelling-a-bone', 'dog-smelling-a-bone'), (b'dog-with-belt-walking-with-a-man', 'dog-with-belt-walking-with-a-man'), (b'dog-with-first-aid-kit-bag', 'dog-with-first-aid-kit-bag'), (b'dog-with-owner', 'dog-with-owner'), (b'man-carrying-a-dog-with-a-belt-to-walk', 'man-carrying-a-dog-with-a-belt-to-walk'), (b'man-combing-a-dog', 'man-combing-a-dog'), (b'man-on-his-knees-to-cuddle-his-dog', 'man-on-his-knees-to-cuddle-his-dog'), (b'man-throwing-a-disc-and-dog-jumping-to-catch-it', 'man-throwing-a-disc-and-dog-jumping-to-catch-it'), (b'paws-up-dog-playing-with-a-man', 'paws-up-dog-playing-with-a-man'), (b'facebook-square', 'facebook-square'), (b'google-plus-square', 'google-plus-square'), (b'pinterest-square', 'pinterest-square'), (b'twitter-square', 'twitter-square')], max_length=120),
        ),
    ]
