# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0014_dog_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='cost',
            field=models.FloatField(default=240, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogStatus',
            field=models.CharField(choices=[('looking', 'Looking for a home'), ('found', 'Found a home'), ('success', 'Success storie')], default='looking', max_length=8, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='neutered',
            field=models.BooleanField(default=True, verbose_name='Neutered'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('extra small', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra large', 'Extra Large')], max_length=15, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='standard_info',
            field=models.BooleanField(default=True, verbose_name='Standard Info'),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='details',
            field=models.CharField(max_length=400, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='icon',
            field=models.CharField(blank=True, choices=[(b'', 'Select an icon'), (b'dog-and-a-man', 'dog-and-a-man'), (b'dog-and-pets-house', 'dog-and-pets-house'), (b'dog-bitting-a-stick-playing-with-a-man', 'dog-bitting-a-stick-playing-with-a-man'), (b'dog-checked-by-a-veterinary', 'dog-checked-by-a-veterinary'), (b'dog-having-a-bubbles-bath', 'dog-having-a-bubbles-bath'), (b'dog-in-front-of-a-man', 'dog-in-front-of-a-man'), (b'dog-learning-man-instructions', 'dog-learning-man-instructions'), (b'dog-playing-with-a-man', 'dog-playing-with-a-man'), (b'dog-pooping', 'dog-pooping'), (b'dog-puppy-and-his-owner-looking-to-opposite-directions', 'dog-puppy-and-his-owner-looking-to-opposite-directions'), (b'dog-puppy-sitting-in-front-of-his-man', 'dog-puppy-sitting-in-front-of-his-man'), (b'dog-smelling-a-bone', 'dog-smelling-a-bone'), (b'dog-with-belt-walking-with-a-man', 'dog-with-belt-walking-with-a-man'), (b'dog-with-first-aid-kit-bag', 'dog-with-first-aid-kit-bag'), (b'dog-with-owner', 'dog-with-owner'), (b'man-carrying-a-dog-with-a-belt-to-walk', 'man-carrying-a-dog-with-a-belt-to-walk'), (b'man-combing-a-dog', 'man-combing-a-dog'), (b'man-on-his-knees-to-cuddle-his-dog', 'man-on-his-knees-to-cuddle-his-dog'), (b'man-throwing-a-disc-and-dog-jumping-to-catch-it', 'man-throwing-a-disc-and-dog-jumping-to-catch-it'), (b'paws-up-dog-playing-with-a-man', 'paws-up-dog-playing-with-a-man'), (b'facebook-square', 'facebook-square'), (b'google-plus-square', 'google-plus-square'), (b'pinterest-square', 'pinterest-square'), (b'twitter-square', 'twitter-square')], max_length=120, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='logo',
            field=models.ImageField(upload_to='uploads/rescue', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='website',
            field=models.URLField(verbose_name='Website'),
        ),
    ]
