# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 22:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0015_auto_20160709_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Body'),
        ),
    ]
