# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0015_auto_20170825_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='oldie',
            field=models.BooleanField(default=False, verbose_name='Oldie'),
        ),
    ]
