# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0016_status_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoints',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
