# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0017_keypoints_is_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
