# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-25 20:29
from __future__ import unicode_literals

from django.db import migrations


def create_filters(app, schema_editor):
    Filter = app.get_model("dogs", "Filter")
    f = Filter(name="Puppies", position=0)
    f.save()
    f = Filter(name="Dogs", position=1)
    f.save()
    f = Filter(name="Oldies", position=2)
    f.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0018_auto_20170912_2123'),
    ]

    operations = [
        migrations.RunPython(create_filters),
    ]
