# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0018_auto_20160710_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='is_void',
        ),
        migrations.RemoveField(
            model_name='dogphoto',
            name='is_void',
        ),
        migrations.RemoveField(
            model_name='keypoints',
            name='is_void',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_void',
        ),
    ]
