# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-25 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0019_auto_20170925_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='oldie',
        ),
    ]
