# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0019_auto_20160710_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('looking', 'Looking for a home'), ('found', 'Found a home'), ('success', 'Success storie')], default='looking', max_length=8),
        ),
    ]
