# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0020_remove_dog_oldie'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, verbose_name='Youtube url')),
                ('position', models.PositiveIntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Youtube Video',
                'verbose_name_plural': 'Youtube Videos',
            },
        ),
    ]
