# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0020_dog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('position',), 'verbose_name': 'Dog', 'verbose_name_plural': 'Dogs'},
        ),
        migrations.AddField(
            model_name='dog',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
