# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0021_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='hold',
            field=models.BooleanField(default=False, verbose_name='Medical Hold'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='cost',
            field=models.FloatField(default=265, verbose_name='Cost'),
        ),
    ]
