# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0022_auto_20190325_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='arrival',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='status',
            name='show_arrival_date',
            field=models.BooleanField(default=False, verbose_name='Show arrival date'),
        ),
    ]
