# Generated by Django 2.2 on 2019-04-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0023_auto_20190416_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.Status'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='rescue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dogs.Rescue'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1),
        ),
        migrations.AlterField(
            model_name='dogphoto',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Select an icon'), ('dog-and-a-man', 'dog-and-a-man'), ('dog-and-pets-house', 'dog-and-pets-house'), ('dog-bitting-a-stick-playing-with-a-man', 'dog-bitting-a-stick-playing-with-a-man'), ('dog-checked-by-a-veterinary', 'dog-checked-by-a-veterinary'), ('dog-having-a-bubbles-bath', 'dog-having-a-bubbles-bath'), ('dog-in-front-of-a-man', 'dog-in-front-of-a-man'), ('dog-learning-man-instructions', 'dog-learning-man-instructions'), ('dog-playing-with-a-man', 'dog-playing-with-a-man'), ('dog-pooping', 'dog-pooping'), ('dog-puppy-and-his-owner-looking-to-opposite-directions', 'dog-puppy-and-his-owner-looking-to-opposite-directions'), ('dog-puppy-sitting-in-front-of-his-man', 'dog-puppy-sitting-in-front-of-his-man'), ('dog-smelling-a-bone', 'dog-smelling-a-bone'), ('dog-with-belt-walking-with-a-man', 'dog-with-belt-walking-with-a-man'), ('dog-with-first-aid-kit-bag', 'dog-with-first-aid-kit-bag'), ('dog-with-owner', 'dog-with-owner'), ('man-carrying-a-dog-with-a-belt-to-walk', 'man-carrying-a-dog-with-a-belt-to-walk'), ('man-combing-a-dog', 'man-combing-a-dog'), ('man-on-his-knees-to-cuddle-his-dog', 'man-on-his-knees-to-cuddle-his-dog'), ('man-throwing-a-disc-and-dog-jumping-to-catch-it', 'man-throwing-a-disc-and-dog-jumping-to-catch-it'), ('paws-up-dog-playing-with-a-man', 'paws-up-dog-playing-with-a-man'), ('facebook-square', 'facebook-square'), ('google-plus-square', 'google-plus-square'), ('pinterest-square', 'pinterest-square'), ('twitter-square', 'twitter-square')], max_length=120, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.Dog'),
        ),
    ]
