# Generated by Django 2.2 on 2019-04-25 19:37

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0024_auto_20190423_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='Promoted on homepage'),
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='homepage',
            field=image_cropping.fields.ImageRatioField('image', '1110x624', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='homepage'),
        ),
    ]
