# Generated by Django 2.2 on 2019-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0025_auto_20190425_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogphoto',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='Promoted on homepage'),
        ),
    ]
