# Generated by Django 2.2 on 2020-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0027_auto_20200324_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponsorshipInfoLinks',
            new_name='SponsorshipInfoLink',
        ),
    ]
