# Generated by Django 2.2 on 2020-03-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0028_auto_20200324_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipinfolink',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='sponsorshipinfolink',
            name='link',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='sponsorshipinfolink',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
