# Generated by Django 2.2 on 2020-04-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0031_sponsorsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorsubmission',
            name='sponsor_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dogs.SponsorshipLevel'),
        ),
        migrations.AlterField(
            model_name='sponsorshiplevel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sponsorsubmission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Phone'),
        ),
    ]
