# Generated by Django 2.2 on 2020-04-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0032_auto_20200404_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorshiplevel',
            old_name='price',
            new_name='cost',
        ),
    ]
