# Generated by Django 2.2 on 2020-04-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0033_auto_20200404_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorsubmission',
            name='sponsor_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.SponsorshipLevel'),
        ),
    ]
