# Generated by Django 2.2 on 2020-04-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0034_auto_20200404_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorsubmission',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sponsorsubmission',
            name='sponsor_level',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='dogs.SponsorshipLevel'),
        ),
    ]
