# Generated by Django 2.2 on 2020-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0035_auto_20200404_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rescue', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
