# Generated by Django 2.2 on 2020-04-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0036_auto_20200404_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue',
            name='logo',
            field=models.ImageField(upload_to='uploads/rescue', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='website',
            field=models.URLField(verbose_name='Website'),
        ),
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('value', models.CharField(max_length=30, verbose_name='value')),
                ('position', models.PositiveIntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
