# Generated by Django 2.2 on 2020-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0037_auto_20200404_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sponsor_status',
            field=models.CharField(blank='', default='', max_length=30, verbose_name='Sponsorship status'),
        ),
    ]
