# Generated by Django 2.2 on 2020-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0038_dog_sponsor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sponsor_status',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Sponsorship status'),
        ),
    ]
