# Generated by Django 3.0.8 on 2020-07-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0039_auto_20200404_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='cost',
            field=models.FloatField(default='300', verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='dogphoto',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='sponsorshipinfolink',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='sponsorshipinfolink',
            name='link',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='sponsorsubmission',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog'),
        ),
    ]
