# Generated by Django 2.2 on 2020-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0040_auto_20200725_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='cost',
            field=models.FloatField(default=300, verbose_name='Cost'),
        ),
    ]
