# Generated by Django 3.2.7 on 2021-09-30 12:18

from django.db import migrations, models
import django_extensions.db.fields


def create_medical_hold(apps, schema_editor):
    Hold = apps.get_model("dogs", "Hold")
    medical = Hold()
    medical.name = 'Medical Hold'
    medical.description = 'medical reasons'
    medical.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0041_auto_20200726_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='hold',
            field=models.BooleanField(default=False, verbose_name='On Hold'),
        ),
        migrations.RunPython(create_medical_hold),
    ]
