# Generated by Django 3.2.7 on 2021-09-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0042_auto_20210930_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='hold_type',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='dogs.hold'),
        ),
    ]
