version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
        environment:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/circle_test?sslmode=disable
          ENV: testing
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - restore_cache:
          key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: install dependencies
          command: pipenv install --dev -r requirements.dev.txt
      - save_cache:
          key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - /home/circleci/.local/share/virtualenvs
            - /home/circleci/.cache/pip
            - /home/circleci/.cache/pipenv
            - ./Pipfile.lock
            - ./Pipfile
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pipenv run pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
