# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'images')),
                ('strapline', models.CharField(max_length=200, verbose_name='Strap Line')),
                ('subline', models.CharField(max_length=400, verbose_name='Sub Line')),
                ('position', models.PositiveIntegerField(default=0)),
                ('itemlink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.node')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AlterField(
            model_name='modulelist',
            name='module',
            field=models.CharField(choices=[(b'Adoption', 'Adoptions'), (b'Success', 'Success')], max_length=200, verbose_name='Module'),
        ),
    ]
