# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160720_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
