# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160615_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='map_address',
        ),
    ]
