# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_map_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelist',
            name='module',
            field=models.CharField(choices=[(b'dogs:AdoptionList', 'Adoption List'), (b'Success', 'Success')], max_length=200, verbose_name='Module'),
        ),
    ]
