# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160720_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelist',
            name='module',
            field=models.CharField(max_length=200, verbose_name='Module'),
        ),
    ]
