# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:29
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160617_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageheader',
            name='cropped',
            field=image_cropping.fields.ImageRatioField(b'image', '1110x624', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropped'),
        ),
    ]
