# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160812_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.IntegerField(choices=[(1, b'Published'), (3, b'Unpublished'), (2, b'Draft')], default=1),
        ),
    ]
