# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 20:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160814_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('intrested_in', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Adopting', 'Adopting'), ('Fostering', 'Fostering'), ('Other', 'Other')], default='Adopting', max_length=100, verbose_name='Intrested In'), size=None)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
