# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepageheader_cropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_home_page',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
