# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_node_is_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
    ]
