# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_intrestsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrestsubmission',
            name='intrested_in',
        ),
        migrations.AddField(
            model_name='intrestsubmission',
            name='adopting',
            field=models.BooleanField(default=True, verbose_name='Adopting'),
        ),
        migrations.AddField(
            model_name='intrestsubmission',
            name='fostering',
            field=models.BooleanField(default=False, verbose_name='Fostering'),
        ),
        migrations.AddField(
            model_name='intrestsubmission',
            name='other',
            field=models.BooleanField(default=False, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='fosteringsubmission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='fosteringsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='intrestsubmission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='intrestsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
