# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-27 22:35
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170827_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrestsubmission',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title'),
        ),
    ]
