# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-12 20:55
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_intrestsubmission_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrestsubmission',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name'),
        ),
    ]
