# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20160712_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.FormModel'),
        ),
    ]
