# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170912_2055'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='empty',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='externallink',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modulelist',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='node',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sociallink',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='concent',
            field=models.BooleanField(default=False, verbose_name='I give consent for data I enter into this form to be stored and processed by SOS Romanian Rescue South West'),
            preserve_default=False,
        ),
    ]
