# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180109_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='concent',
            new_name='consent',
        ),
    ]
