# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20160715_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
