# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180109_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='consent',
            field=models.BooleanField(verbose_name='I give consent for data I enter into this form to be stored and processed by SOS Romanian Rescue South West and I am over 18'),
        ),
    ]
