# Generated by Django 2.2 on 2019-04-23 19:29

from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180109_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empty',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Empty Item', 'verbose_name_plural': 'Empty Items'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'External Link', 'verbose_name_plural': 'External Links'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Site node', 'verbose_name_plural': 'Site nodes'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft'), 'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.AlterModelManagers(
            name='empty',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='externallink',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='modulelist',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sociallink',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='homepageheader',
            name='itemlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='nav_icon',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=200, null=True, verbose_name='Navigation Icon'),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pages.node', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='node',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (3, 'Unpublished'), (2, 'Draft')], default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='form',
            field=models.CharField(blank=True, choices=[('ContactForm', 'Contact Form'), ('FosteringForm', 'Fostering Form')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=200, verbose_name='Social Type'),
        ),
    ]
