# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_auto_20160715_2124'),
        ('pages', '0013_auto_20160717_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='form2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.FormModel'),
        ),
    ]
