# Generated by Django 2.2 on 2019-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20190423_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='consent',
            field=models.BooleanField(verbose_name='I give consent for data I enter into this form to be stored and processed by SOS Romanian Rescue South West and I am over 18'),
        ),
    ]
