# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_page_form2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='form2',
        ),
    ]
