# Generated by Django 2.2 on 2020-03-24 21:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190425_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('consent', models.BooleanField(verbose_name='I give consent for data I enter into this form to be stored and processed by SOS Romanian Rescue South West and I am over 18')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
