# Generated by Django 2.2 on 2020-03-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0029_auto_20200324_2036'),
        ('pages', '0015_sponsorsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorsubmission',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dogs.Dog'),
        ),
    ]
