# Generated by Django 2.2 on 2020-04-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_sponsorsubmission_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorSubmission',
        ),
    ]
