# Generated by Django 3.0.8 on 2020-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_delete_sponsorsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='node',
            name='active_url_helper',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),                
        migrations.AlterField(
            model_name='page',
            name='form',
            field=models.CharField(blank=True, choices=[('ContactForm', 'Contact Form'), ('FosteringForm', 'Fostering Form')], default='', max_length=100),
        ),
    ]
