# Generated by Django 3.0.8 on 2020-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200725_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nav_icon',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], default='', max_length=200, null=True, verbose_name='Navigation Icon'),
        ),
        migrations.AlterField(
            model_name='node',
            name='nav_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Navigation Title'),
        ),
        migrations.AlterField(
            model_name='node',
            name='title_tag',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Title Tag'),
        ),
    ]
