# Generated by Django 3.0.8 on 2020-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200725_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nav_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Navigation Title'),
        ),
    ]
