# Generated by Django 3.0.8 on 2020-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200725_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='title_tag',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title Tag'),
        ),
    ]
