# Generated by Django 3.0.8 on 2020-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200725_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nav_icon',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], default='', max_length=200, verbose_name='Navigation Icon'),
        ),
    ]
