# Generated by Django 3.2.3 on 2021-05-15 09:12

from django.db import migrations
from pages.models import Page

def addDonatePage(apps, schema_editor):
    #Page = apps.get_model('pages', 'Page')
    donatePage = Page.objects.get(slug='donate')
    donatePage.slug = 'donate'
    donatePage.title = 'SOS Romanian Rescues South West'
    donatePage.nav_title = 'Donate'

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20200725_0943'),
    ]

    operations = [
    ]
