# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, b'Published'), (3, b'Unpublished'), (2, b'Draft')], default=1),
        ),
    ]
