# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 20:54
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photocomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
