# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 21:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photocomp', '0002_competition_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='competition',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Body'),
        ),
    ]
