# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocomp', '0003_auto_20170623_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
