# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photocomp', '0005_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='copetition',
            new_name='competition',
        ),
    ]
